site_name: WekaDeeplearning4j
theme: readthedocs
repo_url: https://github.com/Waikato/wekaDeeplearning4j
site_description: WekaDeeplearning4j Documentation
nav:
    - Home: index.md
    - Installation: install.md


    - User Guide:
        - 'Getting Started': 'user-guide/getting-started.md'
        - 'Loading Data': 'user-guide/data.md'
        - 'Model Zoo': 'user-guide/model-zoo.md'
        - 'Natural Language Processing': 'user-guide/nlp.md'
        - 'Progress Manager': 'user-guide/progress-manager.md'
    - Examples:
        - 'Image Feature Extraction': 'examples/featurize-mnist.md'
        - 'Classifying a Custom Dataset': 'examples/classifying-your-own.md'
        - 'Classifying the MNIST Dataset': 'examples/classifying-mnist.md'
        - 'Classifying the Iris Dataset': 'examples/classifying-iris.md'
        - 'Classifying the IMDB Dataset': 'examples/classifying-imdb.md'
    - Troubleshooting: troubleshooting.md
